apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-webhook-cfg
  labels:
    app: env-injector
webhooks:
  - name: env-injector.wh.net
    admissionReviewVersions: [v1beta1, v1]
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: env-injector-webhook-svc
        namespace: admin
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJZUdKSXMwaTlKZVV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1UVXhOalUwTURsYUZ3MHpOVEF6TVRNeE5qVTVNRGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPWTUvRG15R0lJM1ZWbnh4NVg4VlZjdWc3UjlVbGV0OHIwVUs2SlQ3ZGdhbDltcWt0TlpNVThDTDIKMTg5VVE1dHA0L2dXOE84WTZ3RW5JclJsN25MTTJEZVRadDVXbHViWHpyQmFySGE3RFV4d0t3akszbEU0SHNaQgpIZ1J1QjNTYkMzd0xPMDhQVDNZdktsMzNyQy9WN2Rtc0p0NnZjTnhMYU5NZVdPWXlaOGcxNC91c1FsOE5rQ3JXCnNxY0lXNlJlV3FCVDJySUFKSE1VbU1wbHdiL25RMXR6UWRaa1N4a2pyZ3ZHcERybGdkLzdaQnFzSm85UGdJaC8KSE1ERkVIbXF3N054cExrMzZMQUNmZnBONmkyVUE2RFJ3L05HRTh2R29EUVFxTFBIcko4MWd3RS8vS2VTQUlOUQordFJCSUlXSW1XOU1meXNXVlNQb24xdFRCVkdyQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSaTJkWWFPNlVjb1YyOURLY1M5R2hrTk9tWHNqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQWVwdG12MjhGTwptVGNsdkoycjl3N2JmVVJRVW1KSkxpUlJIUzdPNktYaXhTVE1NV0ZiczVRTzZZSWdGbjBKOWtCZ29WWjA5K1ZGCkhQVHlsWnNWVkFZZkVDM1czWmlxd29FNWIwQmFybGF6S3RLUGYwakF0TGlCbXNlbnJKNGRHeFZMc09OZ0UySEQKZ2Q1N1k0UmtTajNLZFVjSGgweUViRU9zcFV2WEpqL3dzTXEyTmoyZzU2a0JPdFVIWXJNNlZMOEJGTXZrZnlQRgplSDM0VGhoSkpvcTNSS0crTVNiTi92bVFhZjBFN0EwdUZ4S3JHK2lPMmhZdFpXczR5MFowTStMWnJ2cWtaaWtuClU5VUdNc3ZQSWtUMFFkTzE3elZQQXAyMHBNbFNWbmtvN2tZQzRDaDdUUysvQXozR1JaMDVqZ0hNcWtxZEZqcFgKTzg2WHpkOXczc0ZSCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        wh/envInjector: enabled
