apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: env-injector-webhook-cfg
  labels:
    app: env-injector
webhooks:
  - name: env-injector.wh.net
    admissionReviewVersions: [v1beta1, v1]
    sideEffects: NoneOnDryRun
    clientConfig:
      service:
        name: env-injector-webhook-svc
        namespace: injector
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTGUzY0I3WGVOUWt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBek1qSXhOekV3TlRsYUZ3MHpOVEF6TWpBeE56RTFOVGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMzTVA1ODVXWnZpblc0MXhFbDlHTHoycW9QOVVRZVNIR3NlV0xOYitvcGszTEtHT2p4dUdRWUp6bTUKWWxILzhHYjdEbkZVaTg2Z0g4eDRkbzJMa0VWei9ValB0RmhyUEtYQUthOTlBQldvV05iN01xaUZKL00zNnlydQpicXRnRjlGaE91SVY4QnJvd0JNTVBZV0pXSDM3RU9LaFZlc09VU2RsYzc3clFIMi9FR0pMY0RSbHdsOUZHc01CCk5RNlFWMWVQbkJVSS8zMC9EUml5K1BIa2l1RkFJbU1qWmZvdE5NZFEyK2phblNsNU80T1M5ZHRNdlZ0MXBYLysKeGR0K3ZRMlJ5Qm9uMW5heTJHY2g4THNQanlYd3lXbTJianJLZ0xSeTcxQWowKzFrcHo0aVNRckRUQmRJS05acwpLYyt2cCtEKzBZN2NtQ1FOTlhzRFo3YjZoUXZsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJURWFEd21IQWJveE94aWJVTHZKcHJEZVdUTHNUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQSsrL1EvK2ZnZwpZNzZnamI4UFpjNUpEQWQvbm14RHFoeStySVVvTUZ6RGVzaVlXQ09udzdDdVFkRkZ1YlFEcGJKb3k5OUt0QTRMCmFDWEZpLzNVbVl6S3dqTHNSTWo0NEJSaldZT2grYmFQSWdnTEQ4YktGWDIrOXRmMDJHRTZncDQ2eXBkWDZLQXoKTUhXZGx3bkpaNmloRmp5WlFjWmZNcVhZdHZwU24xa2lTNUtmN2thV1p5K0hveERFMnV1YVNnZU9ybkhtOFV5dwpONmlrZUlwWENEQXV1QWFDN3piZ3p6SjE5dnZCWGJ1NzNmaGdzOU41OGFqcmx3Y290ZE5Vd0xYa0pNZHRSZTBTCjk2RjAzWVNncnRRRXBjdURVMnpOVFBtdkZta3FOeEREMVF3MVZQTXlPVUYwbTdWTEhSb1JSS3RNaXNhck93NDQKcWtZd2pJU1VUbGgxCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        wh/envInjector: enabled
