apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
        inject-env: "true"
        app-type: "web"
#      annotations:
#        some-annotation-key-1: some_annotation_value_1
    spec:
#      dnsConfig:
#        options:
#          - name: use-vc
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            - labelSelector:
#                matchExpressions:
#                  - key: app
#                    operator: In
#                    values:
#                      - sleep
#              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: sleep
        image: hmctspublic.azurecr.io/docker-curl
        command: ["sleep","1d"]
        imagePullPolicy: Always
#        env:
#          - name: SOME_KEY_1
#            value: SOME_VALUE_1
